apps/core/urls.py
"""
Module    : urls
Date      : May, 2015
Author(s) : Matt Gathu <mattgathu@gmail.com>
Desc      : Veritza montenegro urls patterns

"""

from django.conf.urls import url

from apps.core import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^datasets/$', views.DatasetsView.as_view(), name='datasets'),

    url(r'^datasets/public-officials/$', views.PublicOfficialsView.as_view(), name='public-officials'),
    url(r'^datasets/public-officials/(?P<pk>\d+)/$', views.PublicOfficialDetailsView.as_view(), name='public-officials'),

    url(r'^companies/$', views.CompaniesView.as_view(), name='companies'),
    url(r'^companies/(?P<pk>\d+)/$', views.CompanyDetailsView.as_view(), name='companies'),

    url(r'^datasets/company-members/$', views.CompanyMembersView.as_view(), name='company-members'),
    url(r'^datasets/company-members/(?P<pk>\d+)/$', views.CompanyMemberDetailsView.as_view(), name='company-members'),

    url(r'^datasets/family-members/$', views.FamilyMembersView.as_view(), name='family-members'),
    url(r'^datasets/family-members/(?P<pk>\d+)/$', views.FamilyMemberDetailsView.as_view(), name='family-members'),

    url(r'^datasets/public-procurements/$', views.PublicProcurementsView.as_view(), name='public-procurements'),
    url(r'^datasets/public-procurements/(?P<pk>\d+)/$', views.PublicProcurementDetailsView.as_view(), name='public-procurements'),

    url(r'^datasets/bidder-companies/$', views.BidderCompaniesView.as_view(), name='bidder-companies'),
    url(r'^datasets/bidder-companies/(?P<pk>\d+)/$', views.BidderCompanyDetailsView.as_view(), name='bidder-companies'),

    url(r'^datasets/elections-contributions/$', views.ElectionsContributionsView.as_view(), name='elections-contributions'),
    url(r'^datasets/elections-contributions/(?P<pk>\d+)/$', views.ElectionsContributionsDetailsView.as_view(), name='elections-contributions'),

    url(r'^datasets/public-official-companies/$', views.PublicOfficialCompaniesView.as_view(), name='public-official-companies'),
    url(r'^datasets/public-official-companies/(?P<pk>\d+)/$', views.PublicOfficialCompanyDetailsView.as_view(), name='public-official-companies'),

    url(r'^datasets/conflict-interests/$', views.ConflictInterestsView.as_view(), name='conflict-interests'),
    url(r'^datasets/conflict-interests/(?P<pk>\d+)/$', views.ConflictInterestDetailsView.as_view(), name='conflict-interests'),

    url(r'^datasets/family-member-companies/$', views.FamilyMemberCompaniesView.as_view(), name='family-member-companies'),
    url(r'^datasets/family-member-companies/(?P<pk>\d+)/$', views.FamilyMemberCompanyDetailsView.as_view(), name='family-member-companies'),

    url(r'^datasets/conflict-interest-family-members/$', views.ConflictInterestFamilyMembersView.as_view(), name='conflict-interest-family-members'),
    url(r'^datasets/conflict-interest-family-members/(?P<pk>\d+)/$', views.ConflictInterestFamilyMemberDetailsView.as_view(), name='conflict-interest-family-members'),


]

urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from apps.core import views as core_views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^serbia/', include('apps.serbia.urls', namespace='serbia')),
    url(r'^usa/', include('apps.usa.urls', namespace='usa')),
    url(r'^montenegro/', include('apps.core.urls', namespace='montenegro')),
    url(r'^', include('apps.corex.urls')),


) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('django.views.static',
                        (r'media/(?P<path>.*)', 'serve',
                         {'document_root': settings.MEDIA_ROOT}), )

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

apps/core/views.py
from datetime import datetime

from django.db.models import Q, Prefetch, CharField, TextField
from django.db import IntegrityError
from django.views.generic import View, TemplateView
from django.views.generic.detail import DetailView
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest

from django_tables2 import SingleTableView
from report_tools.views import ReportView

from apps.core.reports import *
from apps.core.models import *
from apps.core.tables import *


from django.contrib.auth.decorators import login_required

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class HomeView(TemplateView):
    template_name = 'core/details/montenegro_home.html'


class DatasetsView(TemplateView):
    template_name = 'core/details/montenegro_datasets.html'


class FaqView(TemplateView):
    template_name = 'faq.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class DatasetsView(LoginRequiredMixin, TemplateView):
    template_name = 'core/details/montenegro_datasets.html'


class SubscriptionView(View):

    def post(self, request, **kwargs):
        user = request.user
        dataset = request.POST.get('dataset', '')
        action = request.POST.get('action', '')
        app = request.POST.get('app_label', None)
        message = ''

        if action == 'subscribe':
            try:
                user.subscribe(dataset, app)
                message = 'Successfully subscribed for {0}'.format(dataset)
            except IntegrityError as e:
                return redirect(request.path)

        elif action == 'unsubscribe':
            user.unsubscribe(dataset, app)
            message = 'Successfully unsubscribed from {0}'.format(dataset)

        else:
            return redirect(request.META.get('HTTP_REFERER'))

        return redirect(request.META.get('HTTP_REFERER'))


class ScrapersView(LoginRequiredMixin, TemplateView):
    template_name  = 'scrapers.html'

    def get_context_data(self, **kwargs):
        context = super(ScrapersView, self).get_context_data(**kwargs)
        context['projects'] = [
            {
                'name': 'montenegro',
                'spiders': []
            }
        ]

        # TODO: remove the static data
        #       and get the data from scrapyd (through its API)
        context['projects'][0]['spiders'] = [
            {
                'name': 'companies',
                'status': 'running',
                'last_run': datetime(2015, 04, 14, 16, 32)
            },
            {
                'name': 'procurements',
                'status': 'pending',
                'last_run': datetime(2015, 04, 14, 15, 17)
            },
            {
                'name': 'public-officials',
                'status': 'finished',
                'last_run': datetime(2015, 04, 14, 12, 02)
            },
        ]
        return context


class SearchView(LoginRequiredMixin, TemplateView):
    template_name = 'search_results.html'
    searched_classes = [
        PublicOfficial, Company, CompanyMember, PublicProcurement, ElectionsContributions,
        FamilyMember,
    ]

    # TODO: search term need to be at least 3 chars long
    def get(self, request, *args, **kwargs):
        """
        Search all char and text fields of all the models in self.searched_classes.
        Return the search results in the follwing form:
        [
            {
                'model': ' model itself ',
                'model_meta': ' model options ',
                'model_name': ' model name ',
                'objects': 'filtered query set by the search term'
            },
            {...},
            {...}
        ]
        """
        search = request.GET.get('search')
        context = self.get_context_data(**kwargs)
        context['search'] = search
        context['results_count'] = 0

        # Don't search at all if search term is not at least 3 chars long
        if len(search) >= 3:
            datasets = []

            # Prepare filters for every searched class and execute the queries
            # by searching in all char/text fields
            for model in self.searched_classes:
                filters = [
                    Q(**{field.name + '__icontains': search})
                    for field in model._meta.fields if isinstance(field, (CharField, TextField))
                ]
                query = filters.pop()
                for item in filters:
                    query |= item

                # Execute SQL query to get the results for this model
                objects = model.objects.select_related().filter(query)

                # Add info for this class in the data returned
                datasets.append({
                    'model': model,
                    'model_meta': model._meta,
                    'model_name': model.__name__,
                    'objects': objects
                })
                context['results_count'] += len(objects)

            context['datasets'] = datasets

        return self.render_to_response(context)


class DatasetView(SingleTableView):
    template_name = 'core/list.html'
    stats_template = 'core/stats/empty.html'
    report = None
    filter_class = None

    def get_queryset(self):
        queryset = super(DatasetView, self).get_queryset()
        queryset = queryset.select_related().all()

        search = self.request.GET.get('search')
        if search:
            filters = [
                Q(**{field.name + '__icontains': search})
                for field in queryset.model._meta.fields if isinstance(field, (models.CharField, models.TextField))
            ]
            query = filters.pop()
            for item in filters:
                query |= item

            queryset = queryset.filter(query)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(DatasetView, self).get_context_data(**kwargs)
        context['stats_template'] = self.stats_template
        context['search'] = self.request.GET.get('search', '')
        if self.report:
            context['report'] = self.report
        return context


class PublicOfficialsView(LoginRequiredMixin, DatasetView, ReportView):
    model = PublicOfficial
    table_class = PublicOfficialTable
    stats_template = 'core/stats/public_officials.html'
    report = PublicOfficialsReport()

    def get_queryset(self):
        queryset = super(PublicOfficialsView, self).get_queryset()
        prefetch = Prefetch('publicofficialreport_set', queryset=PublicOfficialReport.objects.all().order_by('-year'), to_attr='reports')
        return queryset.prefetch_related(prefetch).all()


class PublicOfficialDetailsView(LoginRequiredMixin, DetailView):
    model = PublicOfficial
    template_name = 'core/details/public_official.html'

    def get_object(self, **kwargs):
        obj = super(self.__class__, self).get_object(**kwargs)
        obj.reports = PublicOfficialReport.objects.filter(official_id=obj.id)
        obj.official_companies = PublicOfficialCompany.objects.select_related('company').filter(official_id=obj.id)
        return obj


class CompaniesView(LoginRequiredMixin, DatasetView):
    model = Company
    table_class = CompanyTable
    stats_template = 'core/stats/companies.html'
    report = CompaniesReport()

    def get_queryset(self):
        queryset = super(self.__class__, self).get_queryset()
        return queryset.prefetch_related('companymember_set', 'biddercompany_set').all()


class CompanyDetailsView(LoginRequiredMixin, DetailView):
    model = Company
    template_name = 'core/details/company.html'

    def get_object(self, **kwargs):
        obj = super(self.__class__, self).get_object(**kwargs)
        obj.company_members = CompanyMemberTitle.objects.select_related('company_member').filter(company_registration_number=obj.registration_number)
        obj.company_procurements = [bidder_company.procurement for bidder_company in BidderCompany.objects.select_related().filter(company_id=obj.id)]
        return obj


class CompanyMembersView(LoginRequiredMixin, DatasetView):
    model = CompanyMember
    table_class = CompanyMemberTable

    def get_queryset(self):
        queryset = super(self.__class__, self).get_queryset()
        # 'company' field needs to be explicitly requested here as
        # it is null=True and not select_related by default
        return queryset.select_related('company').all()


class CompanyMemberDetailsView(LoginRequiredMixin, DetailView):
    model = CompanyMember
    template_name = 'core/details/company_member.html'

    def get_object(self, **kwargs):
        obj = super(self.__class__, self).get_object(**kwargs)
        obj.titles = CompanyMemberTitle.objects.filter(company_member_id=obj.id)
        return obj


class FamilyMembersView(LoginRequiredMixin, DatasetView, ReportView):
    model = FamilyMember
    table_class = FamilyMemberTable
    stats_template = 'core/stats/family_members.html'
    report = FamilyMembersReport()

    def get_queryset(self):
        queryset = super(FamilyMembersView, self).get_queryset()
        prefetch = Prefetch('public_official__publicofficialreport_set',
            queryset=PublicOfficialReport.objects.all().order_by('-year'),
            to_attr='public_official_reports')
        # return queryset.prefetch_related(prefetch).all()
        return queryset.select_related('public_official').all()


class FamilyMemberDetailsView(LoginRequiredMixin, DetailView):
    model = FamilyMember
    template_name = 'core/details/family_member.html'

    def get_queryset(self):
        queryset = super(FamilyMemberDetailsView, self).get_queryset()
        return queryset.select_related()


class PublicProcurementsView(LoginRequiredMixin, DatasetView, ReportView):

apps/core/templates/core/details/company.html
{% extends 'core/dataset_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block content %}
	<ol class="breadcrumb">
	  <li><a href="{% url 'montenegro:index' %}">Home</a></li>
	  <li><a href="{% url 'montenegro:datasets' %}">Datasets</a></li>
	  <li><a href="{% url 'montenegro:companies' %}">Companies</a></li>
	  <li>{{ object.id }}</li>
	</ol>

	<h3>Company profile</h3>
	<div class="page-header">{{ object.name }}</div>

	<div class="panel panel-default">
		<div class="panel-heading">Basic information</div>
		<div class="panel-body">
			<table class="table table-bordered">
				<tr> <td>Registration number</td> <td>{{ object.registration_number }}</td> </tr>
				<tr> <td>Identification number</td> <td>{{ object.identification_number }}</td> </tr>
				<tr> <td>Full name</td> <td>{{ object.full_name }}</td> </tr>
				<tr> <td>Company type</td> <td>{{ object.economic_activity }}</td> </tr>
				<tr> <td>Address</td> <td>{{ object.address }}</td> </tr>
				<tr> <td>Mail address</td> <td>{{ object.mail_address }}</td> </tr>
				<tr> <td>Registration date</td> <td>{{ object.registration_date }}</td> </tr>
				<tr> <td>Location</td> <td>{{ object.location }}</td> </tr>
				<tr> <td>Activity</td> <td>{{ object.activity }}</td> </tr>
			</table>
		</div>
	</div>

	<div class="panel panel-success">
		<div class="panel-heading">Company Members ({{ object.company_members|length }})</div>
			{% if object.company_members %}
			<div class="panel-body">
				<table class="table table-bordered">
				<tr>
					<th>Name</th>
					<th>Title</th>
					<th>Share</th>
				</tr>
				{% for member in object.company_members %}
					<tr>
						<td><a href="{% url 'montenegro:company-members' member.id %}">{{ member.company_member.full_name }}</a></td>
						<td>{{ member.title|default:"" }}</td>
						<td>{{ member.share|default:"" }}</td>
					</tr>
				{% endfor %}
				</table>
			</div>
			{% endif %}
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">Public Procurements ({{ object.company_procurements|length }})</div>
			{% if object.company_procurements %}
			<div class="panel-body">
				<table class="table table-bordered">
					<tr>
						<th>Number</th>
						<th>Title</th>
						<th>Subject</th>
						<th>Value</th>
						<th>Notice</th>
					</tr>
					{% for procurement in object.company_procurements %}
					<tr>
						<td><a href="{% url 'montenegro:public-procurements' procurement.id %}">{{ procurement.number }}</a></td>
						<td>{{ procurement.title }}</td>
						<td>{{ procurement.subject }}</td>
						<td>{{ procurement.value }} &euro;</td>
						<td>{{ procurement.record_type }}</td>
					</tr>
					{% endfor %}
				</table>
			</div>
			{% endif %}
	</div>
{% endblock %}

apps/core/templates/core/details/company_member.html
{% extends 'core/dataset_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block content %}
	<ol class="breadcrumb">
	  <li><a href="{% url 'montenegro:index' %}">Home</a></li>
	  <li><a href="{% url 'montenegro:datasets' %}">Datasets</a></li>
	  <li><a href="{% url 'montenegro:company-members' %}">Company member</a></li>
	  <li>{{ object.id }}</li>
	</ol>

	<h3>Company member profile</h3>
	<div class="page-header">{{ object.full_name }}</div>

	<div class="panel panel-default">
		<div class="panel-heading">Basic information</div>
		<div class="panel-body">
			<table class="table table-bordered">
				<tr> <td>First name</td> <td>{{ object.first_name }}</td> </tr>
				<tr> <td>Last name</td> <td>{{ object.last_name }}</td> </tr>
				<tr> <td>Company registration number</td> <td>{{ object.company_registration_number }}</td> </tr>
			</table>
		</div>
	</div>

	<div class="panel panel-success">
		<div class="panel-heading">Company</div>
			{% if object.company %}
			<div class="panel-body">
				<table class="table table-bordered">
				<tr>
					<th>Registration number</th>
					<th>Name</th>
					<th>Registration date</th>
					<th>Location</th>
				</tr>
					<tr>
						<td><a href="{% url 'montenegro:companies' object.company.id %}">{{ object.company.registration_number }}</a></td>
						<td>{{ object.company.full_name }}</td>
						<td>{{ object.company.registration_date }}</td>
						<td>{{ object.company.location }}</td>
					</tr>
				</table>
			</div>
			{% endif %}
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">Company member details</div>
			{% if object.titles %}
			<div class="panel-body">
				<table class="table table-bordered">
					<tr>
						<th>Title</th>
						<th>Share</th>
					</tr>
					{% for title in object.titles %}
					<tr>
						<td>{{ title.title|default:"" }}</td>
						<td>{{ title.share|default:"" }}</td>
					</tr>
					{% endfor %}
				</table>
			</div>
			{% endif %}
	</div>
{% endblock %}

apps/core/templates/core/details/montenegro_base.html
{% extends "veritza_base.html" %}

{% block datasetsurl %}<a href="{% url 'montenegro:datasets' %}">{% endblock %}

apps/core/templates/core/details/montenegro_datasets.html
{% extends "core/details/montenegro_base.html" %}
{% load veritza_utils %}
{% load humanize %}
{% load i18n %}

{% block content %}
<div class="row">

    <!-- LEFT PANE -->
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">Datasets - obtained from government agencies</div>
            <div class="panel-body">

            <div class="row">
                <a href="{% url 'montenegro:public-officials' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/public-official-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Public Officials ({{ 'Public officials'|count_objects|intcomma }})</div></a>
						<div>{% include 'core/subscription_form_include.html' with dataset_name='PublicOfficial' %}</div>
						<div style="font-size: 9pt">Names and titles of all the public officials in Montenegro - public record registry of Montenegrin public officials obtained from the Commission for the Prevention of Conflict of Interest in Montenegro <a href="http://www.konfliktinteresa.me" target="_top">www.konfliktinteresa.me</a>.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:family-members' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/family-member-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Family Members ({{ 'Family members'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FamilyMember' %}</div>
                        <div style="font-size: 9pt">Family Members Names of all the public officials in Montenegro - public record registry of Montenegrin public officials obtained from the Commission for the Prevention of Conflict of Interest in Montenegro <a href="http://www.konfliktinteresa.me" target="_top">www.konfliktinteresa.me</a>.</div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'montenegro:companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Companies ({{ 'Companies'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='Company' %}</div>
                        <div style="font-size: 9pt">List of all the companies in Montenegro - public record registry of Montenegrin Central Registry of Business Entities <a href="http://www.crps.me/" target="_top">www.crps.me</a>.</div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'montenegro:company-members' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Company Owners ({{ 'Company members'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='CompanyMember' %}</div>
                        <div style="font-size: 9pt">List of all the company owners in Montenegro - public record registry of Montenegrin Central Registry of Business Entities <a href="http://www.crps.me/" target="_top">www.crps.me</a>.</div>
                        <br/>
                    </div>
            </div>


            <div class="row">
                <a href="{% url 'montenegro:public-procurements' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/public-procurement-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Public Procurements ({{ 'Public procurements'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='PublicProcurement' %}</div>
                        <div style="font-size: 9pt">List of all the public procurements in Montenegro - public record registry of Public Procurement Administration of Montenegro <a href="http://portal.ujn.gov.me/" target="_top">www.ujn.gov.me</a>.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:bidder-companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/bidder-company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Vendors & Suppliers ({{ 'Bidder companies'|count_objects|intcomma }})</div> </a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='BidderCompany' %}</div>
                        <div style="font-size: 9pt">List of all the companies in Montenegro that have been contracted by the governments - public record registry of Public Procurement Administration of Montenegro <a href="http://portal.ujn.gov.me/" target="_top">www.ujn.gov.me</a>.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:elections-contributions' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/elections-contributions-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Elections Contributions ({{ 'Elections contributions'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ElectionsContributions' %}</div>
                        <div style="font-size: 9pt">List of all the election contributions in Montenegro - public record registry of State Election Commision of Montenegro <a href="http://rik.co.me/" target="_top">www.rik.co.me</a></div>
                    </div>

            </div>

            </div>
        </div>

    </div>

    <!-- RIGHT PANE -->
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">Veritzas - public records data integrations</div>
            <div class="panel-body">

            <div class="row">
                <a href="{% url 'montenegro:public-official-companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Public Official Companies ({{ 'Public officials companies'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='PublicOfficialCompany' %}</div>
                        <div style="font-size: 9pt">List of all the Montenegrin companies that have a public official name in the list of founders, directors or board members - combined public record registry.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:conflict-interests' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/conflict-interest-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Public Official Companies in Procurement ({{ 'Conflicts of interest'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ConflictInterest' %}</div>
                        <div style="font-size: 9pt">List of all the government procurements in Montenegro where the winning company has a public official as a founder, director or board member - combined public record registry.</div>
                    </div>
            </div>


            <div class="row">
                <a href="{% url 'montenegro:family-member-companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/family-member-company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Family Member Companies ({{ 'Family member companies'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FamilyMemberCompany' %}</div>
                        <div style="font-size: 9pt">List of all the Montenegrin companies that have a family member of a public in the list of founders, directors or board members - combined public record registry.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:conflict-interest-family-members' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/conflict-interest-family-member-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Family Member Companies in Procurement ({{ 'Conflicts of interest (Family Members)'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ConflictInterestFamilyMember' %}</div>
  						<div style="font-size: 9pt">List of all the government procurements in Montenegro where the winning company has a family member of a public official as a founder, director or board member - combined public record registry.</div>
                    </div>
            </div>

            <div class="row">
                <a href="{% url 'montenegro:elections-contributions' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/elections-contributions-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Political funders companies in Procurement({{ 'Elections contributions'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ElectionsContributions' %}</div>
                        <div style="font-size: 9pt">List of all the procurements of companies owned by individuals that contributed to political party in Montenegro - public record registry of State Election Commision of Montenegro <a href="http://rik.co.me/" target="_top">www.rik.co.me/</a></div>
                    </div>

            </div>
            <div class="row">
                <a href="{% url 'montenegro:elections-contributions' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/elections-contributions-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div class="text" style="font-size: 12pt">Companies political funders in procurement({{ 'Elections contributions'|count_objects|intcomma }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ElectionsContributions' %}</div>
                        <div style="font-size: 9pt">List of all the procurements of companies that contributed to political party in Montenegro - public record registry of State Election Commision of Montenegro <a href="http://rik.co.me/" target="_top">www.rik.co.me/</a></div>
                    </div>

            </div>

            </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}