apps/usa/urls.py
"""
Module    : urls
Date      : May, 2015
Author(s) : Matt Gathu <mattgathu@gmail.com>
Desc      : Veritza usa urls patterns

"""
# ============================================================================
# necessary imports
# ============================================================================
from django.conf.urls import url

from . import views

# ============================================================================
# url patterns
# ============================================================================
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^companies/$', views.CompaniesView.as_view(), name='federal-companies'),
    url(r'^datasets/$', views.DatasetsView.as_view(), name='datasets'),
    url(r'^procurements/$', views.ProcurementsView.as_view(), name='federal-procurement'),
    url(r'^electioncontribs/$', views.ElectionContributionsView.as_view(), name='elections-contributions'),
    url(r'^irsexempt/$', views.IrsExemptOrgsView.as_view(), name='irs-exempt-organizations'),
    url(r'^secfilings/$', views.SecFilingsView.as_view(), name='securities-and-exchange-commission-filings'),
    url(r'^toxicsfacilities/$', views.ToxicsFacilitiesView.as_view(), name='toxics-facilities'),
    url(r'^oshaebsa/$', views.OshaEbsasView.as_view(), name='osha-employee-benefits-security-adminstration-enforcements'),
    url(r'^oshainsp/$', views.OshaInspectionsView.as_view(), name='occupational-safety-and-health-inspections'),
    url(r'^cpscrecalls/$', views.CpscRecallsView.as_view(), name='consumer-product-safety-commission-recalls'),
    url(r'^cpscviols/$', views.CpscRecallViolationsView.as_view(), name='consumer-product-safety-commission-recall-violations'),
    url(r'^disclosures/$', views.FinancialDisclosuresView.as_view(), name='federal-financial-disclosures'),
    url(r'^candidates/$', views.CandidatesView.as_view(), name='election-candidates'),

    url(r'^companies/(?P<pk>\d+)/$', views.CompanyDetailView.as_view(), name='federal-companies'),
    url(r'^procurements/(?P<pk>\d+)/$', views.ProcurementDetailView.as_view(), name='federal-procurement'),
    url(r'^electioncontribs/(?P<pk>\d+)/$', views.ElectionContributionDetailView.as_view(), name='elections-contributions'),
    url(r'^irsexempt/(?P<pk>\d+)/$', views.IrsExemptOrgDetailView.as_view(), name='irs-exempt-organizations'),
    url(r'^secfilings/(?P<pk>\d+)/$', views.SecFilingDetailView.as_view(), name='securities-and-exchange-commission-filings'),
    url(r'^toxicsfacilities/(?P<pk>\d+)/$', views.ToxicsFacilityDetailView.as_view(), name='toxics-facilities'),
    url(r'^oshaebsa/(?P<pk>\d+)/$', views.OshaEbsaDetailView.as_view(), name='osha-employee-benefits-security-adminstration-enforcements'),
    url(r'^oshainsp/(?P<pk>\d+)/$', views.OshaInspectionDetailView.as_view(), name='occupational-safety-and-health-inspections'),
    url(r'^cpscrecalls/(?P<pk>\d+)/$', views.CpscRecallDetailView.as_view(), name='consumer-product-safety-commission-recalls'),
    url(r'^cpscviols/(?P<pk>\d+)/$', views.CpscRecallViolationDetailView.as_view(), name='consumer-product-safety-commission-recall-violations'),
    url(r'^disclosures/(?P<pk>\d+)/$', views.FinancialDisclosureDetailView.as_view(), name='federal-financial-disclosures'),
    url(r'^candidates/(?P<pk>\d+)/$', views.CandidateDetailView.as_view(), name='election-candidates'),

    url(r'^funderscompanies/$', views.FundersCompanies.as_view(), name='funderscompanies'),
    url(r'^funderscompaniesprocurement', views.FundersCompaniesProcurement.as_view(), name='funderscompaniesprocurement'),

    url(r'^search', views.SearchView.as_view(), name='search'),

]

# ============================================================================
# EOF
# ============================================================================

urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from apps.core import views as core_views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^serbia/', include('apps.serbia.urls', namespace='serbia')),
    url(r'^usa/', include('apps.usa.urls', namespace='usa')),
    url(r'^montenegro/', include('apps.core.urls', namespace='montenegro')),
    url(r'^', include('apps.corex.urls')),


) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('django.views.static',
                        (r'media/(?P<path>.*)', 'serve',
                         {'document_root': settings.MEDIA_ROOT}), )

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

apps/usa/views.py
"""
views

"""
from django.views.generic import TemplateView, DetailView
from django_tables2 import SingleTableView
import watson

from apps.core.views import LoginRequiredMixin

from . import models, tables


class CandidatesView(SingleTableView):
    """list of candidates view"""
    model = models.FedCandidate
    table_class = tables.CandidateTable
    template_name = 'usa_list.html'


class CandidateDetailView(DetailView):
    model = models.FedCandidate
    template_name = 'usa_candidate.html'


class CompaniesView(SingleTableView):
    """list of companies view"""
    model = models.FedCompany
    table_class = tables.CompanyTable
    template_name = 'usa_list.html'


class CompanyDetailView(DetailView):
    model = models.FedCompany
    template_name = 'usa_company.html'


class ElectionContributionsView(SingleTableView):
    """list of election contributions"""
    model = models.FedElectionContribution
    table_class = tables.ElectionContributionTable
    template_name = 'usa_list.html'


class ElectionContributionDetailView(DetailView):
    model = models.FedElectionContribution
    template_name = 'usa_contribution.html'


class DatasetsView(LoginRequiredMixin, TemplateView):
    """Datasets index view """
    template_name = 'usa_datasets.html'

    def get_context_data(self, **kwargs):
        context = super(DatasetsView, self).get_context_data(**kwargs)
        context['companies_no'] = models.FedCompany.objects.count()
        context['disclosures_no'] = models.FedFinancialDisclosure.objects.count()
        context['procurements_no'] = models.FedProcurement.objects.count()
        context['irsexempt_no'] = models.FedIrsExemptOrg.objects.count()
        context['secfilings_no'] = models.FedSecFiling.objects.count()
        context['toxics_no'] = models.FedToxicsFacility.objects.count()
        context['oshaebsa_no'] = models.FedOshaEbsa.objects.count()
        context['oshainsp_no'] = models.FedOshaInspection.objects.count()
        context['cpscrecalls_no'] = models.FedCpscRecall.objects.count()
        context['cpscviol_no'] = models.FedCpscRecallViolation.objects.count()
        context['candidates_no'] = models.FedCandidate.objects.count()
        context['econtribs_no'] = models.FedElectionContribution.objects.count()
        context['officials_no'] = 0
        context['funderscompanies_no'] = models.FedFunderCompany.objects.count()
        context['funderscompaniesproc_no'] = models.FedFunderCompanyProcurement.objects.count()

        return context


class FinancialDisclosuresView(SingleTableView):
    """list of Financial disclosures"""
    model = models.FedFinancialDisclosure
    table_class = tables.FinancialDisclosureTable
    template_name = 'usa_list.html'


class FinancialDisclosureDetailView(DetailView):
    model = models.FedFinancialDisclosure
    template_name = 'usa_financial_disclosure.html'


class FundersCompanies(SingleTableView):
    """list of election donors/funders companies"""
    model = models.FedFunderCompany
    table_class = tables.FunderCompanyTable
    template_name = 'usa_list.html'


class FundersCompaniesProcurement(SingleTableView):
    """list of companies in procurement owned by political funders"""
    model = models.FedFunderCompanyProcurement
    table_class = tables.FunderCompanyProcurementTable
    template_name = 'usa_list.html'


class IndexView(TemplateView):
    """Index view """
    template_name = 'usa_home.html'


class IrsExemptOrgsView(SingleTableView):
    """list of IRS Exempt Organizations"""
    model = models.FedIrsExemptOrg
    table_class = tables.IrsExemptOrgTable
    template_name = 'usa_list.html'


class IrsExemptOrgDetailView(DetailView):
    model = models.FedIrsExemptOrg
    template_name = 'usa_irsexempt_org.html'


class ProcurementsView(SingleTableView):
    """List of procurements """
    model = models.FedProcurement
    table_class = tables.ProcurementTable
    template_name = 'usa_list.html'


class ProcurementDetailView(DetailView):
    model = models.FedProcurement
    template_name = 'usa_procurement.html'


class SecFilingsView(SingleTableView):
    """list of SEC filings"""
    model = models.FedSecFiling
    table_class = tables.SecFilingTable
    template_name = 'usa_list.html'


class SecFilingDetailView(DetailView):
    model = models.FedSecFiling
    template_name = 'usa_sec_filing.html'


class ToxicsFacilitiesView(SingleTableView):
    """list of Toxics facilities"""
    model = models.FedToxicsFacility
    table_class = tables.ToxicsFacilityTable
    template_name = 'usa_list.html'


class ToxicsFacilityDetailView(DetailView):
    model = models.FedToxicsFacility
    template_name = 'usa_toxics_facility.html'


class OshaEbsasView(SingleTableView):
    """list of OSHA EBSA"""
    model = models.FedOshaEbsa
    table_class = tables.OshaEbsaTable
    template_name = 'usa_list.html'


class OshaEbsaDetailView(DetailView):
    model = models.FedOshaEbsa
    template_name = 'usa_osha_ebsa.html'


class OshaInspectionsView(SingleTableView):
    """list of OSHA inspections"""
    model = models.FedOshaInspection
    table_class = tables.OshaInspectionTable
    template_name = 'usa_list.html'


class OshaInspectionDetailView(DetailView):
    model = models.FedOshaInspection
    template_name = 'usa_osha_insp.html'


class CpscRecallsView(SingleTableView):
    """list of CPSC Recalls"""
    model = models.FedCpscRecall
    table_class = tables.CpscRecallTable
    template_name = 'usa_list.html'


class CpscRecallDetailView(DetailView):
    model = models.FedCpscRecall
    template_name = 'usa_cpsc_recall.html'


class CpscRecallViolationsView(SingleTableView):
    """list of CPSC Recall Violations"""
    model = models.FedCpscRecallViolation
    table_class = tables.CpscRecallViolationTable
    template_name = 'usa_list.html'


class CpscRecallViolationDetailView(DetailView):
    model = models.FedCpscRecallViolation
    template_name = 'usa_cpsc_recall_violation.html'


class SearchView(LoginRequiredMixin, TemplateView):
    """usa search view"""
    template_name = 'usa_search_results.html'

    def get(self, request, *args, **kwargs):
        """search term"""
        search_term = request.GET.get('search')
        context = self.get_context_data(**kwargs)
        context['search'] = search_term
        context['results_count'] = 0
        context['datasets'] = []

        _models = [models.FedCandidate, models.FedCompany, models.FedCpscRecall,
                   models.FedCpscRecallViolation, models.FedElectionContribution,
                   models.FedFinancialDisclosure, models.FedIrsExemptOrg,
                   models.FedOshaEbsa, models.FedOshaInspection,
                   models.FedProcurement, models.FedSecFiling,
                   models.FedToxicsFacility]

        for model in _models:
            results = watson.filter(model, search_term)
            context['results_count'] += len(results)
            context['datasets'].append({
                'model': model,
                'model_meta': model._meta,
                'model_name': model.__name__,
                'objects': results
            })

        return self.render_to_response(context)


# ============================================================================
# EOF
# ============================================================================

apps/usa/templates/usa_base.html
{% extends "veritza_base.html" %}

{% block datasetsurl %}<a href="{% url 'usa:datasets' %}">{% endblock %}
{% block search %}<form style="padding-top: 8px;" action="{% url 'usa:search' %}"> {% endblock %}

apps/usa/templates/usa_candidate.html
{% extends 'usa_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block content %}
  <ol class="breadcrumb">
    <li><a href="{% url 'usa:index' %}">Home</a></li>
    <li><a href="{% url 'usa:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'usa:election-candidates' %}">Election Candidates</a></li>
    <li>{{ object.id }}</li>
  </ol>

  <h3>Election Candidate</h3>
    <div class="page-header">{{ object.cand_name }}</div>

    <div class="panel panel-default">
      <div class="panel-heading">Basic information</div>
      <div class="panel-body">
        <table class="table table-bordered">
          <tr> <td>Candidate ID</td> <td>{{ object.cand_id }}</td> </tr>
          <tr> <td>Candidate Name</td> <td>{{ object.cand_name|capfirst }}</td> </tr>
          <tr> <td>Party Affiliation</td> <td>{{ object.cand_pty_affiliation }}</td> </tr>
          <tr> <td>Election Year</td> <td>{{ object.cand_election_yr }}</td> </tr>
          <tr> <td>Office</td> <td>{{ object.cand_office }}</td> </tr>
          <tr> <td>Office State</td> <td>{{ object.cand_office_st }}</td> </tr>
          <tr> <td>Office District Number</td> <td>{{ object.cand_office_district }}</td> </tr>
          <tr> <td>Incumbent Challenger Status</td> <td>{{ object.cand_ici }}</td> </tr>
          <tr> <td>Status</td> <td>{{ object.cand_status }}</td> </tr>
          <tr> <td>Campaign Committee</td> <td>{{ object.cand_pcc }}</td> </tr>
          <tr> <td>State</td> <td>{{ object.cand_st|upper }}</td> </tr>
          <tr> <td>City</td> <td>{{ object.cand_city }}</td> </tr>
          <tr> <td>Street</td> <td>{{ object.cand_st1 }}</td> </tr>
          <tr> <td>Street 2</td> <td>{{ object.cand_st2 }}</td> </tr>
          <tr> <td>Zip Code</td> <td>{{ object.cand_zip }}</td> </tr>
        </table>
      </div>
    </div>

{% endblock %}

apps/usa/templates/usa_company.html
{% extends 'usa_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block content %}
  <ol class="breadcrumb">
    <li><a href="{% url 'usa:index' %}">Home</a></li>
    <li><a href="{% url 'usa:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'usa:federal-companies' %}">Companies</a></li>
    <li>{{ object.id }}</li>
  </ol>

  <h3>Company profile</h3>
    <div class="page-header">{{ object.name|lower|title }}</div>

    <div class="panel panel-default">
      <div class="panel-heading">Basic information</div>
      <div class="panel-body">
        <table class="table table-bordered">
          <tr> <td>Company name</td> <td>{{ object.name|lower|title }}</td> </tr>
          <tr> <td>DUNS number</td> <td>{{ object.duns_num }}</td> </tr>
          <tr> <td>Founders</td> <td>{% if object.founders %} {{ object.founders }} {%endif %}</td> </tr>
          <tr> <td>Company type</td> <td>{{ object.type|lower|title }}</td> </tr>
          <tr> <td>Address</td> <td>{{ object.address }}</td> </tr>
          <tr> <td>Registration date</td> <td>{{ object.reg_date }}</td> </tr>
          <tr> <td>URL</td> <td><a target='_' href="{{ object.url|default_if_none:"#" }}">url</a></td> </tr>
        </table>
      </div>
    </div>

{% endblock %}

apps/usa/templates/usa_contribution.html
{% extends 'usa_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block content %}
  <ol class="breadcrumb">
    <li><a href="{% url 'usa:index' %}">Home</a></li>
    <li><a href="{% url 'usa:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'usa:elections-contributions' %}">Election Contributions</a></li>
    <li>{{ object.id }}</li>
  </ol>

  <h3>Election Contribution</h3>
    <div class="page-header">{{ object.name }}</div>

    <div class="panel panel-default">
      <div class="panel-heading">Basic information</div>
      <div class="panel-body">
        <table class="table table-bordered">
          <tr> <td>Amendment</td> <td>{{ object.amndt_ind }}</td> </tr>
          <tr> <td>Candidate ID</td> <td>{{ object.cand_id }}</td> </tr>
          <tr> <td>City</td> <td>{{ object.city }}</td> </tr>
          <tr> <td>Committee ID</td> <td>{{ object.cmte_id }}</td> </tr>
          <tr> <td>Employer</td> <td>{{ object.employer }}</td> </tr>
          <tr> <td>Entity Type</td> <td>{{ object.entity_tp }}</td> </tr>
          <tr> <td>File Number</td> <td>{{ object.file_num }}</td> </tr>
          <tr> <td>Microfilm Location</td> <td>{{ object.image_num }}</td> </tr>
          <tr> <td>Memo Code</td> <td>{{ object.memo_cd }}</td> </tr>
          <tr> <td>Memo Text</td> <td>{{ object.memo_text }}</td> </tr>
          <tr> <td>Contributor Name</td> <td>{{ object.name }}</td> </tr>
          <tr> <td>Occupation</td> <td>{{ object.occupation }}</td> </tr>
          <tr> <td>Other ID</td> <td>{{ object.other_id }}</td> </tr>
          <tr> <td>Report Type</td> <td>{{ object.rpt_tp }}</td> </tr>
          <tr> <td>State</td> <td>{{ object.state }}</td> </tr>
          <tr> <td>FEC Record Number</td> <td>{{ object.sub_id }}</td> </tr>
          <tr> <td>Transaction ID</td> <td>{{ object.tran_id }}</td> </tr>
          <tr> <td>Transaction Amount</td> <td>{{ object.transaction_amt }}</td> </tr>
          <tr> <td>Transaction Date</td> <td>{{ object.transaction_dt }}</td> </tr>
          <tr> <td>Transaction Primary-General Indicator</td> <td>{{ object.transaction_pgi }}</td> </tr>
          <tr> <td>Transaction Type</td> <td>{{ object.transaction_tp }}</td> </tr>
          <tr> <td>Zip Code</td> <td>{{ object.zip_code }}</td> </tr>
          <tr> <td>URL</td> <td><a target='_' href="{{ object.url|default_if_none:"#" }}">url </a></td> </tr>
        </table>
      </div>
    </div>


{% endblock %}

apps/usa/templates/usa_datasets.html
{% extends "usa_base.html" %}
{% load veritza_utils %}
{% load humanize %}
{% load i18n %}

{% block content %}
<div class="row">
  <!-- LEFT PANE -->
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading">Datasets - obtained from government agencies</div>
        <div class="panel-body">



            <div class="row">
                <a href="{% url 'usa:federal-companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Companies ({{ companies_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedCompany,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Companies.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'usa:federal-financial-disclosures' %}">
                    <div class="col-md-2">
                        <i class="fa fa-money fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Financial Disclosures ({{ disclosures_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedFinancialDisclosure,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Financial Disclosures.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'usa:federal-procurement' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/public-procurement-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Public Procurement ({{ procurements_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedProcurement,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Public Procurement.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'usa:irs-exempt-organizations' %}">
                    <div class="col-md-2">
                        <i class="fa fa-certificate fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">IRS Exempt Organizations ({{ irsexempt_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedIrsExemptOrg,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of IRS Exempt Organizations.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:securities-and-exchange-commission-filings' %}">
                    <div class="col-md-2">
                        <i class="fa fa-file-text fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">SEC Filings ({{ secfilings_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedSecFiling,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of SEC  Filings.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:toxics-facilities' %}">
                    <div class="col-md-2">
                        <i class="fa fa-warning fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Toxics Facilites ({{ toxics_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedToxicsFacility,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Toxics Facilities.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:osha-employee-benefits-security-adminstration-enforcements' %}">
                    <div class="col-md-2">
                        <i class="fa fa-cog fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">OSHA EBSA ({{ oshaebsa_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedOshaEbsa,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of OSHA EBSA Enforcements.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'usa:occupational-safety-and-health-inspections' %}">
                    <div class="col-md-2">
                        <i class="fa fa-plus-square fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">OSHA Inspections ({{ oshainsp_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedOshaInspection,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of OSHA Public Safety Inspections.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:consumer-product-safety-commission-recalls' %}">
                    <div class="col-md-2">
                        <i class="fa fa-bell fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">CPSC Recalls ({{ cpscrecalls_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedCpscRecall,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Consumer Product Safety Commission Recalls.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:consumer-product-safety-commission-recall-violations' %}">
                    <div class="col-md-2">
                        <i class="fa fa-bell-o fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">CPSC Violations ({{ cpscviol_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedCpscRecallViolation,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Consumer Product Safety Commission Recalls Violations.
                        </div>
                    </div>

            </div>

            <div class="row">
                <a href="{% url 'usa:election-candidates' %}">
                    <div class="col-md-2">
                        <i class="fa fa-group fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Election Candidates ({{ candidates_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedCandidate,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Elections Canditates.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'usa:elections-contributions' %}">
                    <div class="col-md-2">
                        <i class="fa fa-money fa-3x"></i>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Election Contributions ({{ econtribs_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='FedElectionContribution,usa' app_name='usa' %}</div>
                        <div style="font-size: 9pt">
                            List of Election Contributions.
                        </div>
                    </div>

            </div>



            </div>
        </div>

    </div>

    <!-- RIGHT PANE -->
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">Veritzas - public records data integrations</div>
            <div class="panel-body">

                <div class="row">
                    <a href="{% url 'usa:funderscompanies' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Political Funders Companies ({{ funderscompanies_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='FedFunderCompany,usa' app_name='usa' %}</div>
                            <div style="font-size: 9pt">List of all the USA Federal companies that have a political funder name in the list of founders, directors or board members - combined public record registry.</div>
                        </div>
                </div>

                <div class="row">
                    <a href="{% url 'usa:funderscompaniesprocurement' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Political Funders Companies in procurement ({{ funderscompaniesproc_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='FedFunderCompanyProcurement,usa' app_name='usa' %}</div>
                            <div style="font-size: 9pt">List of all the USA Federal companies that have a political funder name in the list of founders, directors or board members and are listed in goverment procurement.</div>
                        </div>
                </div>




            </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}