apps/serbia/urls.py
"""
Module    : urls
Date      : May, 2015
Author(s) : Matt Gathu <mattgathu@gmail.com>
Desc      : Veritza serbia urls patterns

"""
# ============================================================================
# necessary imports
# ============================================================================
from django.conf.urls import url

from . import views

# ============================================================================
# url patterns
# ============================================================================
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^search', views.SearchView.as_view(), name='search'),

    url(r'^companies/$', views.CompaniesView.as_view(), name='companies'),

    url(r'^companies/(?P<pk>\d+)/$', views.CompanyDetailView.as_view(),
        name='companies'),
    url(r'^datasets/$', views.DatasetsView.as_view(), name='datasets'),

    url(r'^electioncontribs/$', views.ElectionDonationsView.as_view(),
        name='electioncontribs'),
    url(r'^electioncontribs/(?P<pk>\d+)/$',
        views.ElectionDonationDetailView.as_view(), name='election-donations'),
    url(r'^officials/$', views.OfficialsView.as_view(), name='officials'),

    url(r'^officials/(?P<pk>\d+)/$', views.OfficialDetailView.as_view(),
        name='officials'),
    url(r'^procurements/$', views.ProcurementsView.as_view(),
        name='procurements'),
    url(r'^procurements/(?P<pk>\d+)/$', views.ProcurementDetailView.as_view(),
        name='procurements'),
    url(r'^officialscompanies/$', views.OfficialsCompanies.as_view(),
        name='officialscompanies'),
    url(r'^officialscompaniesprocurement/$',
        views.OfficialsCompaniesProcurement.as_view(), name='officialscompaniesprocurement'),
    url(r'^funderscompanies/$',
        views.FundersCompanies.as_view(), name='funderscompanies'),
    url(r'^funderscompaniesprocurement',
        views.FundersCompaniesProcurement.as_view(), name='funderscompaniesprocurement'),
    url(r'^fundingcompaniesprocurement',
        views.FundingCompaniesProcurement.as_view(), name='fundingcompaniesprocurement')
]

# ============================================================================
# EOF
# ============================================================================

urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from apps.core import views as core_views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^serbia/', include('apps.serbia.urls', namespace='serbia')),
    url(r'^usa/', include('apps.usa.urls', namespace='usa')),
    url(r'^montenegro/', include('apps.core.urls', namespace='montenegro')),
    url(r'^', include('apps.corex.urls')),


) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('django.views.static',
                        (r'media/(?P<path>.*)', 'serve',
                         {'document_root': settings.MEDIA_ROOT}), )

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

apps/serbia/views.py
"""
Module    : views
Date      : May, 2015
Author(s) : Matt Gathu <mattgathu@gmail.com>
Desc      : Veritza serbia views


"""
# ============================================================================
# necessary imports
# ============================================================================
from django.views.generic import TemplateView, DetailView
from django_tables2 import SingleTableView

import watson

from apps.core.views import LoginRequiredMixin

from . import models, tables


# ============================================================================
# class based views
# ============================================================================
class CompaniesView(SingleTableView):
    """list of companies view"""
    model = models.Company
    table_class = tables.CompanyTable
    template_name = 'serbia_list.html'


class CompanyDetailView(DetailView):

    model = models.Company
    template_name = 'serbia_company.html'


class DatasetsView(LoginRequiredMixin, TemplateView):
    template_name = 'serbia_datasets.html'

    def get_context_data(self, **kwargs):
        context = super(DatasetsView, self).get_context_data(**kwargs)
        context['officials_no'] = models.Official.objects.count()
        context['companies_no'] = models.Company.objects.count()
        context['procurements_no'] = models.Procurement.objects.count()
        context['edonations_no'] = models.ElectionDonation.objects.count()
        context['offcompanies_no'] = models.OfficialCompany.objects.count()
        context['offcompaniesproc_no'] = models.OfficialCompanyProcurement.objects.count()
        context['funderscompanies_no'] = models.FunderCompany.objects.count()
        context['funderscompaniesproc_no'] = models.FunderCompanyProcurement.objects.count()
        context['fundingcompaniesproc_no'] = models.FundingCompanyProcurement.objects.count()

        return context


class ElectionDonationsView(SingleTableView):
    """list of election donations"""
    model = models.ElectionDonation
    table_class = tables.ElectionDonationTable
    template_name = 'serbia_list.html'


class ElectionDonationDetailView(DetailView):
    model = models.ElectionDonation
    template_name = 'serbia_election_donation.html'


class IndexView(TemplateView):
    template_name = 'serbia_home.html'


class OfficialsView(SingleTableView):
    """list of public officials view"""
    model = models.Official
    table_class = tables.OfficialTable
    template_name = 'serbia_list.html'


class OfficialDetailView(DetailView):
    model = models.Official
    template_name = 'serbia_official.html'


class ProcurementsView(SingleTableView):
    """list of procurement view"""
    model = models.Procurement
    table_class = tables.ProcurementTable
    template_name = 'serbia_list.html'


class ProcurementDetailView(DetailView):
    model = models.Procurement
    template_name = 'serbia_procurement.html'


class OfficialsCompanies(SingleTableView):
    """list of public officials' companies"""
    model = models.OfficialCompany
    table_class = tables.OfficialCompanyTable
    template_name = 'serbia_list.html'


class OfficialsCompaniesProcurement(SingleTableView):
    """list of public officials companies in procurement"""
    model = models.OfficialCompanyProcurement
    table_class = tables.OfficialCompanyProcurementTable
    template_name = 'serbia_list.html'


class FundersCompanies(SingleTableView):
    """list of election donors/funders companies"""
    model = models.FunderCompany
    table_class = tables.FunderCompanyTable
    template_name = 'serbia_list.html'


class FundersCompaniesProcurement(SingleTableView):
    """list of companies in procurement owned by political funders"""
    model = models.FunderCompanyProcurement
    table_class = tables.FunderCompanyProcurementTable
    template_name = 'serbia_list.html'


class FundingCompaniesProcurement(SingleTableView):
    """list of companies that are funders and also are in procurement"""
    model = models.FundingCompanyProcurement
    table_class = tables.FundingCompanyProcurementTable
    template_name = 'serbia_list.html'


class SearchView(LoginRequiredMixin, TemplateView):
    """serbia search view"""
    template_name = 'serbia_search_results.html'

    def get(self, request, *args, **kwargs):
        """search term"""
        search_term = request.GET.get('search')
        context = self.get_context_data(**kwargs)
        context['search'] = search_term
        context['results_count'] = 0
        context['datasets'] = []

        _models = [models.Company, models.ElectionDonation, models.Procurement,
                   models.Official]

        for model in _models:
            results = watson.filter(model, search_term)
            context['results_count'] += len(results)
            context['datasets'].append({
                'model': model,
                'model_meta': model._meta,
                'model_name': model.__name__,
                'objects': results
            })

        return self.render_to_response(context)

# ============================================================================
# EOF
# ============================================================================

apps/serbia/templates/serbia_base.html
{% extends "veritza_base.html" %}

{% block datasetsurl %}<a href="{% url 'serbia:datasets' %}">{% endblock %}
{% block search %}<form style="padding-top: 8px;" action="{% url 'serbia:search' %}"> {% endblock %}

apps/serbia/templates/serbia_companies.html
{% extends 'serbia_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block js %}<script type="text/javascript" src="https://www.google.com/jsapi"></script>{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'serbia:index' %}">Home</a></li>
  <li>{{ table.data.verbose_name_plural }}</li>
</ol>
<div class="page-header"><h3>{{ table.data.verbose_name_plural }}&nbsp;&nbsp;</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Statistics &amp; Charts</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    </div>
  </div>
</div>


{% render_table table %}

{% endblock %}

apps/serbia/templates/serbia_company.html
{% extends 'company_base.html' %}

{% block path %}
  <ol class="breadcrumb">
    <li><a href="{% url 'serbia:index' %}">Home</a></li>
    <li><a href="{% url 'serbia:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'serbia:companies' %}">Companies</a></li>
    <li>{{ object.id }}</li>
  </ol>
  {% endblock path %}

{% block extrarows %}
    <tr> <td>Legal Representative</td> <td>{{ object.legal_rep }}</td> </tr>
    <tr> <td>Members</td> <td>{{ object.members }}</td> </tr>
    <tr> <td>Supervisors</td> <td>{{ object.supervisors }}</td> </tr>
    <tr> <td>Other Individuals</td> <td>{{ object.other_individuals }}</td> </tr>
	<tr> <td>Area</td> <td>{{ object.area }}</td> </tr>
	<tr> <td>ID / Stat Number</td> <td>{{ object.company_id }}</td> </tr>
	<tr> <td>Form</td> <td>{{ object.form }}</td> </tr>

	<tr> <td>Place</td> <td>{{ object.place }}</td> </tr>
	<tr> <td>Tax Number</td> <td>{{ object.tax_number }}</td> </tr>
	<tr> <td>Termination Date</td> <td>{{ object.termination_date }}</td> </tr>
{% endblock %}

apps/serbia/templates/serbia_datasets.html
{% extends "serbia_base.html" %}
{% load veritza_utils %}
{% load humanize %}
{% load i18n %}



{% block content %}
<div class="row">
  <!-- LEFT PANE -->
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading">Datasets - obtained from government agencies</div>
        <div class="panel-body">

        <div class="row">
          <a href="{% url 'serbia:officials' %}">
            <div class="col-md-2">
              <img src="{{ MEDIA_URL }}images/public-official-small.png"></img>
            </div>
            <div class="col-md-8">
              <div style="font-size: 12pt">Public Officials ({{ officials_no }})</div>
          </a>
        	  <div>{% include 'core/subscription_form_include.html' with dataset_name='Official,serbia' app_name='serbia' %}</div>
        	  <div style="font-size: 9pt">
                Names and titles of all the public officials in Serbia - public record registry of Serbian public officials.
               </div>
            </div>
          </div>



            <div class="row">
                <a href="{% url 'serbia:companies' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/company-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Companies ({{ companies_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='Company,serbia' app_name='serbia' %}</div>
                        <div style="font-size: 9pt">
                            List of all the companies in Serbia - public record registry of Serbian Central Registry of Business Entities.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'serbia:procurements' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/public-procurement-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Procurements ({{ procurements_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='Procurement,serbia' app_name='serbia' %}</div>
                        <div style="font-size: 9pt">
                            List of all the public procuments in Serbia.
                        </div>
                    </div>

            </div>


            <div class="row">
                <a href="{% url 'serbia:electioncontribs' %}">
                    <div class="col-md-2">
                        <img src="{{ MEDIA_URL }}images/elections-contributions-small.png"></img>
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 12pt">Election Contributions ({{ edonations_no }})</div></a>
                        <div>{% include 'core/subscription_form_include.html' with dataset_name='ElectionDonation,serbia' app_name='serbia' %}</div>
                        <div style="font-size: 9pt">
                            List of all the election contributions in Serbia.
                        </div>
                    </div>

            </div>




            </div>
        </div>

    </div>

    <!-- RIGHT PANE -->
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">Veritzas - public records data integrations</div>
            <div class="panel-body">

                <div class="row">
                    <a href="{% url 'serbia:officialscompanies' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Public Official Companies ({{ offcompanies_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='OfficialCompany,serbia' app_name='serbia' %}</div>
                            <div style="font-size: 9pt">List of all the Serbian companies that have a public official name in the list of founders, directors or board members - combined public record registry.</div>
                        </div>
                </div>

                <div class="row">
                    <a href="{% url 'serbia:officialscompaniesprocurement' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Public Official Companies in Procurement ({{ offcompaniesproc_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='OfficialCompanyprocurement,serbia' app_name='serbia' %}</div>
                            <div style="font-size: 9pt">List of all the Serbian companies in procurement that have a public official name in the list of founders, directors or board members - combined public record registry.</div>
                        </div>
                </div>


                <div class="row">
                    <a href="{% url 'serbia:funderscompanies' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Political Funders Companies ({{ funderscompanies_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='FunderCompany,serbia' app_name='serbia' %}</div>
                            <div style="font-size: 9pt">List of all the Serbian companies that have a political funder name in the list of founders, directors or board members - combined public record registry.</div>
                        </div>
                </div>

                <div class="row">
                    <a href="{% url 'serbia:funderscompaniesprocurement' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Political Funders Companies in procurement ({{ funderscompaniesproc_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='FunderCompanyProcurement,serbia' app_name='serbia' %}</div>
                            <div style="font-size: 9pt">List of all the Serbian companies that have a political funder name in the list of founders, directors or board members and are listed in goverment procurement.</div>
                        </div>
                </div>


                <div class="row">
                    <a href="{% url 'serbia:fundingcompaniesprocurement' %}">
                        <div class="col-md-2">
                            <img src="{{ MEDIA_URL }}images/official-company-small.png"></img>
                        </div>
                        <div class="col-md-8">
                            <div style="font-size: 12pt">Funding Companies in procurement ({{ fundingcompaniesproc_no }})</div></a>
                            <div>{% include 'core/subscription_form_include.html' with dataset_name='FundingCompanyProcurement,serbia' app_name='serbia' %}</div>
                            <div style="font-size: 9pt">List of all the Serbian companies that are political funders and are listed in government procurement.</div>
                        </div>
                </div>



            </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

apps/serbia/templates/serbia_election_donation.html
{% extends 'election_donation_base.html' %}

{% block path %}
  <ol class="breadcrumb">
    <li><a href="{% url 'serbia:index' %}">Home</a></li>
    <li><a href="{% url 'serbia:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'serbia:electioncontribs' %}">Election Contributions</a></li>
    <li>{{ object.id }}</li>
  </ol>
  {% endblock path %}

{% block extrarows %}
	<tr> <td>Donation</td> <td>{{ object.donation }}</td> </tr>
	<tr> <td>Dues</td> <td>{{ object.dues }}</td> </tr>
	<tr> <td>Kind Donations</td> <td>{{ object.kind_donations }}</td> </tr>
	<tr> <td>Selection</td> <td>{{ object.selection }}</td> </tr>
{% endblock %}

apps/serbia/templates/serbia_election_donations.html
{% extends 'serbia_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block js %}<script type="text/javascript" src="https://www.google.com/jsapi"></script>{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'serbia:index' %}">Home</a></li>
  <li>{{ table.data.verbose_name_plural }}</li>
</ol>
<div class="page-header"><h3>{{ table.data.verbose_name_plural }}&nbsp;&nbsp;</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Statistics &amp; Charts</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    </div>
  </div>
</div>


{% render_table table %}

{% endblock %}

apps/serbia/templates/serbia_home.html
{% extends 'serbia_base.html' %}
{% load i18n %}

{% block content %}

     </br></br></br><div class="text-center"><h1>You've found Veritza Serbia platform!</h1></p>
     <img src="{{ MEDIA_URL }}images/Serbia_and_Montenegro.png"></img>
    <h1><em>We' re not quite there yet - but we're getting there - and we really want you to know when we're ready.</em></h1></br></br>
    <h2>Sign up <a href="{% url 'userena_signup' %}">here</a> to get notified! or get in touch with us <a href="mailto:info@veritza.org" target="_top">info@veritza.org</a></h2></div>

{% endblock %}

apps/serbia/templates/serbia_list.html
{% extends 'serbia_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block js %}<script type="text/javascript" src="https://www.google.com/jsapi"></script>{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Home</a></li>
  <li><a href="{% url 'serbia:datasets' %}">Datasets</a></li>
  <li>{{ table.data.verbose_name_plural }}</li>
</ol>
<div class="page-header"><h3>{{ table.data.verbose_name_plural }}&nbsp;&nbsp;</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Statistics &amp; Charts</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    </div>
  </div>
</div>


{% render_table table %}

{% endblock %}

apps/serbia/templates/serbia_official.html
{% extends 'official_base.html' %}

{% block path %}
  <ol class="breadcrumb">
    <li><a href="{% url 'serbia:index' %}">Home</a></li>
    <li><a href="{% url 'serbia:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'serbia:officials' %}">Officials</a></li>
    <li>{{ object.id }}</li>
  </ol>
  {% endblock path %}

{% block extrarows %}
	<tr> <td>Salaries</td>
		<td>
			{% for x in object.salary_set.all %}
				{{ x.net_income }}<br>
			{% endfor %}
		</td>
	</tr>

    <tr> <td>Real Estates</td>
    	<td>
			{% for x in object.realestate_set.all %}
				{{ x.place }}
			{% endfor %}
            {% for x in object.fixedasset_set.all %}
				{{ x.type_size }}<br>
			{% endfor %}
		</td>
    </tr>

    <tr> <td>Fixed Assets</td>
    	<td>
			{% for x in object.fixedasset_set.all %}
				{{ x.acquisition_basis }}<br>
			{% endfor %}
		</td>
    </tr>

    <tr> <td>Transport</td>
    	<td>
			{% for x in object.transport_set.all %}
				{{ x.brand }}<br>
			{% endfor %}
		</td>
    </tr>

     <tr> <td>Companies</td>
    	<td>
			{% for x in object.companies.all %}
				{{ x.name }}
			{% endfor %}
		</td>
    </tr>

     <tr> <td>Children</td>
    	<td>
			{% for x in object.children.all %}
				{{ x.name }}
			{% endfor %}
		</td>
    </tr>

	<tr> <td>Deposit Savings</td> <td>{% if object.deposit_savings %} Yes {% else %} No {% endif %}</td> </tr>
	<tr> <td>Place</td> <td>{{ object.place }}</td> </tr>
	<tr> <td>Date</td> <td>{{ object.date }}</td> </tr>
{% endblock %}

apps/serbia/templates/serbia_officials.html
{% extends 'serbia_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block js %}<script type="text/javascript" src="https://www.google.com/jsapi"></script>{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Home</a></li>
  <li>{{ table.data.verbose_name_plural }}</li>
</ol>
<div class="page-header"><h3>{{ table.data.verbose_name_plural }}&nbsp;&nbsp;</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Statistics &amp; Charts</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    </div>
  </div>
</div>


{% render_table table %}

{% endblock %}

apps/serbia/templates/serbia_procurement.html
{% extends 'procurement_base.html' %}

{% block path %}
  <ol class="breadcrumb">
    <li><a href="{% url 'serbia:index' %}">Home</a></li>
    <li><a href="{% url 'serbia:datasets' %}">Datasets</a></li>
    <li><a href="{% url 'serbia:procurements' %}">Procurements</a></li>
    <li>{{ object.id }}</li>
  </ol>
  {% endblock path %}

{% block extrarows %}
    <tr> <td>Contracting Authority ID </td><td>{{ object.contracting_auth_id }}</td> </tr>
    <tr> <td>Contracting Authority Address</td><td>{{ object.contracting_auth_address }}</td> </tr>
    <tr> <td>Reason of Default</td><td>{{ object.default_reason }}</td> </tr>
    <tr> <td>ORN code </td><td>{{ object.orn_code }}</td> </tr>
    <tr> <td>Basis of LPP </td><td>{{ object.lpp_basis }}</td> </tr>
    <tr> <td>PPO Reviews </td><td>{{ object.ppo_reviews }}</td> </tr>
    <tr> <td>Procedure Type </td><td>{{ object.procedure_type }}</td> </tr>
    <tr> <td>Vendor's / Supplier's State </td><td>{{ object.suppliers_state }}</td> </tr>
    <tr> <td>Procurement Subject </td><td>{{ object.subject }}</td> </tr>
    <tr> <td>Contract value of purchases (in 000 RSD) </td><td>{{ object.purchases_val_contract }}</td> </tr>
    <tr> <td>Estimate value of purchases (in 000 RSD) </td><td>{{ object.purchases_val_estimate }}</td> </tr>
    <tr> <td>Number of Offers </td><td>{{ object.offers }}</td> </tr>
    <tr> <td>Criterion of selection </td><td>{{ object.selection_criterion }}</td> </tr>
    <tr> <td>Cost of Preparing bids </td><td>{{ object.preparing_bids_cost }}</td> </tr>
    <tr> <td>Date of execution / non-execution </td><td>{% if object.execution_date %} {{ object.execution_date }} {% endif %}</td> </tr>
    <tr> <td>Execution of contract value excl. VAT (in 000 RSD)</td><td>{{ object.execution_value }}</td> </tr>
	<tr> <td>Eq. price</td> <td>{{ object.eq_price }}</td> </tr>
	<tr> <td>Execution / Non-Execution note</td> <td>{{ object.execution_note }}</td> </tr>
	<tr> <td>Types of Cases Procurement</td> <td>{{ object.cases_types }}</td> </tr>
	<tr> <td>Vendor / Supplier name</td> <td>{{ object.supplier_name }}</td> </tr>
	<tr> <td>Vendor / Supplier ID</td> <td>{{ object.supplier_id }}</td> </tr>
	<tr> <td>Vendor's Country</td> <td>{{ object.supplier_country }}</td> </tr>
	<tr> <td>Modifications</td> <td>{{ object.modifications }}</td> </tr>
{% endblock %}

apps/serbia/templates/serbia_procurements.html
{% extends 'serbia_base.html' %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load i18n %}

{% block js %}<script type="text/javascript" src="https://www.google.com/jsapi"></script>{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{% url 'serbia:index' %}">Home</a></li>
  <li>{{ table.data.verbose_name_plural }}</li>
</ol>
<div class="page-header"><h3>{{ table.data.verbose_name_plural }}&nbsp;&nbsp;</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Statistics &amp; Charts</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    </div>
  </div>
</div>


{% render_table table %}

{% endblock %}